services:
  - type: web
    name: vitalchain-web
    runtime: python
    rootDir: vitalchain-web
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -b 0.0.0.0:$PORT server:app
    envVars:
      - key: DATABASE_URL
        sync: false
